version: '2'

services:
  event-app:
    image: lassouedaziz/event:latest
    ports:
      - "8089:8089"
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/eventsProject?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: aziz
      SPRING_DATASOURCE_PASSWORD: aziz

  mysql-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eventsProject
      MYSQL_USER: aziz
      MYSQL_PASSWORD: aziz
    ports:
      - "3307:3306"
